### ISSUE TITLE
Searching for content shows no results

### ISSUE THREAD

**Issue by garret** [ngosang/docker-amule#10]
I have noticed that after I have aMule running on for some time on my Raspberry Pi 4, the searching function seems broken. Searching from both the gui and web interface delivers no results for whatever thing is entered. I have to restart the container to get the function working again. When searching delivers no results, I do not see anything suspicious on the internal aMule log page. Additionally, files download/upload does not seem to be affected.

**Comment by Wibol** [comment]
This is something that also happens to me even on aMule for desktop, and always when I am connected to "eMule Security". Connecting to another server solves it for me. Have you tried it?

**Comment by garret** [comment]
I am starting to think that all these issues are due to the way aMule was built/packaged for debian. I have been using for more than 6 months a custom base image from alpine and aMule there never gave me any problems (not the KAD graph, or that it needs to be restarted after some time or now the 0 results). 
This was my custom alpine image https://github.com/garret/amule-raspberrypi (forked from another project). I dropped it because I always prefer to rely on other people for updates but I am meditating if I should go back since in any case aMule is not updated that often. Maybe you could reconsider to try aMule on alpine and see if you still have these issues?

**Comment by Wibol** [comment]
My experience is with aMule desktop running on Manjaro XFCE. Now I'm testing this image and that hasn't happened to me yet.

I will try it on Alpine Linux.

**Comment by ngosang** [comment]
I'm testing a new Docker image based on Alpine. I will keep it running for a week to see if the issues are fixed. If everything is OK I'm going to replace the Debian image with this one.

**Comment by garret** [comment]
@ngosang eventually you could consider to try my own alpine-based image in case as starting point. I recently updated to the latest version of aMule.

**Comment by ngosang** [comment]
@garret I'm testing your image :smile:

**Comment by ngosang** [comment]
@garret I tested you Alpine based Docker image for 1 week and I can reproduce all issues present in Debian image.

* Memory leak is there. https://github.com/amule-project/amule/issues/314
* After 1 day aprox, the Amule network traffic and CPU usage stops. I think this is the case your are not able to search. If I click in one ED2K server to connect, it works for another day but it stops working. https://github.com/amule-project/amule/issues/315
*  The KAD graph worked the first 4 days but today aMule crashed just when I clicked in KAD tab in the Web UI. https://github.com/ngosang/docker-amule/issues/8
* In all the issues I can not see error traces

![image](https://user-images.githubusercontent.com/10577978/153657790-30779c0a-e896-4b24-863f-d2b2ab449703.png)

I don't see a reason to move to Alpine for now but I'm in favor to reduce the image size a bit.

**Comment by ngosang** [comment]
I just released 2.3.3-5 with several changes.
* It's based on Alpine Linux (size is only 9 MB now)
* All modifications including Kad stats are optional and they can be disabled
* Implemented mod to auto-restart and share folders recursively => https://github.com/ngosang/docker-amule#modifications

My monitoring stack includes Grafana (web ui dashboard) + Prometheus (metric collector) + cAdvisor (exports docker metrics to Prometheus)
I have more Prometheus exporters for other things. For example, node-exporter to export server stats and blackbox-exporter to check services are up and running.
I also have Alertmanager to receive notification when something goes wrong.

**Comment by ngosang** [comment]
I'm already using your Alpine image and it's working well for me.
I will close this issue if there is no more information in the next weeks.
