### ISSUE TITLE
config pwd but can't login on docker

### ISSUE THREAD

**Issue by ColsonRichard** [ngosang/docker-amule#14]
I having a problem in docker
  docker run -d \
  --name=amule \
  -e PUID=0 \
  -e PGID=0 \
  -e GUI_PWD=123 \
  -e WEBUI_PWD=123 \
...
I can't login using 123.
What is the reason?

**Comment by ColsonRichard** [comment]
I have solved this problem by changing the config configuration

**Comment by ngosang** [comment]
I'm glad you fixed it.
The environment variables `GUI_PWD=123` and `WEBUI_PWD=123` only applies on the first start, if the aMule configuration does not exist. After the passwords are saved they are not modified in the following restarts. If you want to change the passwords, you have to do it by editing the config files.
https://wiki.archlinux.org/title/AMule#Configuration
