### ISSUE TITLE
whats the proper way to mount "my_movies" aka extra share directories?

### ISSUE THREAD

**Issue by gotbletu** [ngosang/docker-amule#15]
the container works fine with **/incoming** just it doesn't detect any extra share directories

tried 1
```
mkdir -vp /media/alfa/amule/{conf,tmp,incoming}
mkdir -vp /media/alfa/amule/incoming/my_movies # path a. not sure which path so i did both
mkdir -vp /media/alfa/amule/my_movies # path b
wget -P /media/alfa/amule/conf https://upd.emule-security.org/nodes.dat # add Kad nodes
podman run -d \
  --name=amule \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Los_Angeles \
  -e GUI_PWD=0123456789 \
  -e WEBUI_PWD=0123456789 \
  -e MOD_AUTO_SHARE_ENABLED=true \
  -e MOD_AUTO_SHARE_DIRECTORIES='/incoming;/my_movies' \
  -p 4711:4711 \
  -p 4712:4712 \
  -p 4662:4662 \
  -p 4665:4665/udp \
  -p 4672:4672/udp \
  -v /media/alfa/amule/conf:/home/amule/.aMule \
  -v /media/alfa/amule/incoming:/incoming \
  -v /media/alfa/amule/tmp:/temp \
  -v /media/bravo/unmanic/media/library:/incoming/my_movies \
  --restart unless-stopped \
  ngosang/amule

```
try 2
`  -v /media/bravo/unmanic/media/library:/my_movies \`

----

P.S i had to use one of these single quotes, double quotes, or backslash escapes around the directories else it complains about directories does not exist
```
  -e MOD_AUTO_SHARE_DIRECTORIES='/incoming;/my_movies' \
  -e MOD_AUTO_SHARE_DIRECTORIES="/incoming;/my_movies" \
  -e MOD_AUTO_SHARE_DIRECTORIES=/incoming\;/my_movies \
```

> Error: requires at least 1 arg(s), only received 0
> -bash: /my_movies: No such file or directory

**Comment by gotbletu** [comment]
oh nvm, had to do `podman restart amule` for it to rescan new files, since the refresh button on the webui doesnt always work

**Comment by ngosang** [comment]
Sorry for the late response. The mods are not part of aMule, they are executed in the Docker entrypoint just once, when the container starts. As you discovered, you have to restart the container to apply changes in the environment variables and to re-discover the files.
