### ISSUE TITLE
Bug? LowID warning and Kad Firewalled

### ISSUE THREAD

**Issue by gotbletu** [ngosang/docker-amule#18]
```
 > eD2k: Connected to eMule Security [5.45.85.226:6584] with LowID
 > Kad: Connected (firewalled)
```

I try disabling all firewall programs (ufw)
I manually port forward on my router also
TCP 4662
UDP 4665/4672

----
Seems like there might be an issue with the container itself? When i use amule program on my desktop (non-container) it works fine, i dont get firewalled or LowID, didnt even need to open any ports, just used UPnP options for port forwarding

I can still download and search just fine with this container but i guess is in a limited scope.
Just wanted to make sure is not just me having this issue.

**Comment by ngosang** [comment]
The container and the documentation is correct => https://github.com/ngosang/docker-amule#application-setup
I'm using this Docker image with high ID opening the ports you mentioned. I'm using Linux btw.

* Make sure your Docker container has the ports mapped to the host. I recommend you to use the docker-compose file.
* Open the ports in your Router and in your firewall. You can use some tool to check the ports => https://www.yougetsignal.com/tools/open-ports/
* Make sure the ports in aMule configuration are the same mapped in Docker and open in the firewall, router.
* Remove and create the container again if you make changes in the ports.

**Comment by gotbletu** [comment]
im using podman instead of docker, maybe thats the issue.

my amule desktop client works fine on my linux desktop without containers (HighID/no firewall issues).
I dont run any firewall services on both machines.
im using arcolinux desktop & ubuntu headless server for containers

anyways ill close this since is an issue on my end.

Thanks for the help tho

**Comment by venator85** [comment]
I also got this issue, in my case the cause was trying to change the external ports via docker.

If you want to change the external port, e.g. from `p 4662:4662` to `-p 46062:4662`, you also need to change the internal port to the same value:

    -p 46062:46062

*and* change the `amule.conf` file: 

    Port=46062

The same applies to other ports.

In general, I think that, in general, the internal port must match the external port and it must also match the public port that you forwarded on your router.

**Comment by gotbletu** [comment]
@venator85 all my port was the same
