### ISSUE TITLE
Upload limitation. does not use all the bandwidth

### ISSUE THREAD

**Issue by mercu01** [ngosang/docker-amule#19]
Hi friend,
I know it's not a problem with your container.
But, I don't get faster upload speeds. I have 15-20mb/s of line to upload.
Do you know any trick? Thanks!
<img width="1248" alt="Captura de Pantalla 2022-06-15 a las 15 32 10" src="https://user-images.githubusercontent.com/9451876/173840142-b60e91fa-7612-4dff-81c1-ec36b0e7dc06.png">
My setup:
![image](https://user-images.githubusercontent.com/9451876/173843718-83fce927-8d11-4a82-91a4-0dc320042746.png)

`[eMule]
AppVersion=2.3.3
Nick=http://www.aMule.org
QueueSizePref=50
MaxUpload=40000
MaxDownload=40000
SlotAllocation=1000
Port=5662
UDPPort=5672
UDPEnable=1
Address=
Autoconnect=1
MaxSourcesPerFile=100
MaxConnections=2000
MaxConnectionsPerFiveSeconds=30
RemoveDeadServer=0
DeadServerRetry=3
ServerKeepAliveTimeout=0
Reconnect=1
Scoresystem=1
Serverlist=0
AddServerListFromServer=0
AddServerListFromClient=0
SafeServerConnect=0
AutoConnectStaticOnly=0
UPnPEnabled=0
UPnPTCPPort=50000
SmartIdCheck=1
ConnectToKad=1
ConnectToED2K=1
TempDir=/temp
IncomingDir=/incoming
ICH=0
AICHTrust=0
CheckDiskspace=0
MinFreeDiskSpace=0
AddNewFilesPaused=0
PreviewPrio=0
ManualHighPrio=0
StartNextFile=0
StartNextFileSameCat=0
StartNextFileAlpha=0
FileBufferSizePref=16
DAPPref=1
UAPPref=1
AllocateFullFile=1
OSDirectory=/home/amule/.aMule
OnlineSignature=0
OnlineSignatureUpdate=5
EnableTrayIcon=0
MinToTray=0
ConfirmExit=1
StartupMinimized=0
3DDepth=10
ToolTipDelay=1
ShowOverhead=0
ShowInfoOnCatTabs=1
VerticalToolbar=0
GeoIPEnabled=1
VideoPlayer=
StatGraphsInterval=3
statsInterval=30
DownloadCapacity=45000
UploadCapacity=45000
StatsAverageMinutes=15
VariousStatisticsMaxValue=100
SeeShare=2
FilterLanIPs=1
ParanoidFiltering=1
IPFilterAutoLoad=1
IPFilterURL=http://upd.emule-security.org/ipfilter.zip
FilterLevel=127
IPFilterSystem=0
FilterMessages=1
FilterAllMessages=0
MessagesFromFriendsOnly=0
MessageFromValidSourcesOnly=1
FilterWordMessages=0
MessageFilter=
ShowMessagesInLog=1
FilterComments=0
CommentFilter=
ShareHiddenFiles=0
AutoSortDownloads=0
NewVersionCheck=0
AdvancedSpamFilter=1
MessageUseCaptchas=1
Language=
SplitterbarPosition=75
YourHostname=
DateTimeFormat=%A, %x, %X
AllcatType=0
ShowAllNotCats=0
SmartIdState=1
DropSlowSources=0
KadNodesUrl=http://upd.emule-security.org/nodes.dat
Ed2kServersUrl=http://upd.emule-security.org/server.met
ShowRatesOnTitle=0
GeoLiteCountryUpdateUrl=https://dl.miyuru.lk/geoip/maxmind/country/maxmind.dat.gz
StatsServerName=Shorty ED2K stats
StatsServerURL=http://ed2k.shortypower.dyndns.org/?hash=
CreateSparseFiles=1
Notifications=0
ShowVersionOnTitle=0
[Browser]
OpenPageInTab=1
CustomBrowserString=
[Proxy]
ProxyEnableProxy=0
ProxyType=0
ProxyName=
ProxyPort=1080
ProxyEnablePassword=0
ProxyUser=
ProxyPassword=
[ExternalConnect]
UseSrcSeeds=0
AcceptExternalConnections=1
ECAddress=
ECPort=4712
ECPassword=2abfffa8be2186dd4755bc807a93027d
UPnPECEnabled=0
ShowProgressBar=1
ShowPercent=1
UseSecIdent=1
IpFilterClients=1
IpFilterServers=1
TransmitOnlyUploadingClients=0
[WebServer]
Enabled=1
Password=2abfffa8be2186dd4755bc807a93027d
PasswordLow=
Port=4711
WebUPnPTCPPort=50001
UPnPWebServerEnabled=0
UseGzip=1
UseLowRightsUser=0
PageRefreshTime=120
Template=AmuleWebUI-Reloaded
Path=amuleweb
[GUI]
HideOnClose=0
[Razor_Preferences]
FastED2KLinksHandler=1
[SkinGUIOptions]
Skin=
[Statistics]
MaxClientVersions=0
[Obfuscation]
IsClientCryptLayerSupported=1
IsCryptLayerRequested=0
IsClientCryptLayerRequired=0
CryptoPaddingLenght=254
CryptoKadUDPKey=138123518
[PowerManagement]
PreventSleepWhileDownloading=0
[UserEvents]
[UserEvents/DownloadCompleted]
CoreEnabled=0
CoreCommand=
GUIEnabled=0
GUICommand=
[UserEvents/NewChatSession]
CoreEnabled=0
CoreCommand=
GUIEnabled=0
GUICommand=
[UserEvents/OutOfDiskSpace]
CoreEnabled=0
CoreCommand=
GUIEnabled=0
GUICommand=
[UserEvents/ErrorOnCompletion]
CoreEnabled=0
CoreCommand=
GUIEnabled=0
GUICommand=
[HTTPDownload]
URL_1=http://upd.emule-security.org/ipfilter.zip
`

**Comment by ngosang** [comment]
The ed2k protocol is slow, has a lot of overhead, and it's CPU intensive, you won't be able to reach bittorrent speeds.

Said that, your configuration looks good to me. Maybe the issue is not on your side. ed2k network is not popular this days so... few clients and many clients have low download speeds. You can monitor aMule resources (CPU and memory) to see if it's reaching some limits.

In the config file I see these options related to upload/download limits:
```
QueueSizePref=50 // I'm not sure about this but it's related to the upload queue. Take a look at the source code => https://github.com/amule-project/amule/search?q=GetQueueSize
MaxUpload=0 // 0 = no upload limit but it's wise to set a big number below your network limit to avoid network congestion. I'm not sure if it's in bytes or bits.
MaxDownload=0 // same as maxupload
SlotAllocation=50 // upload slots, increase this number
MaxSourcesPerFile=300
MaxConnections=500
MaxConnectionsPerFiveSeconds=20 // i don't know how often clients re-connect but we can try 50 ?
```

**Comment by mercu01** [comment]
Hi, friend.
I'll try the parameters you mention.
Thanks a lot!
