### ISSUE TITLE
update server.met

### ISSUE THREAD

**Issue by scascalesp** [ngosang/docker-amule#2]
Hello
The web interface miss option to add server.met url. For ecxample: http://update.adunanza.net/servers.met
Thx

**Comment by ngosang** [comment]
Yes, the Web UI does not support that feature. You can request it in the official aMule repository but the project is not under active development.

You will find a file called `amule.conf` in the config folder.
```
    volumes:
      - <fill_amule_configuration_path>:/home/amule/.aMule
```
Stop aMule container, edit the file and start the container again. The configuration will be maintained between restarts.

**Comment by scascalesp** [comment]
Hello
What i must edit?
![image](https://user-images.githubusercontent.com/89306506/230804819-15a03f64-a334-4677-bac6-d2c6c4e2a199.png)

**Comment by ngosang** [comment]
`server.met` is a binary file. You can not edit it with a text editor. The file will be created by aMule or you can download it from here =>http://shortypower.org/
