### ISSUE TITLE
Problem adding new theme

### ISSUE THREAD

**Issue by acetaku** [ngosang/docker-amule#20]
Hi, ngosang.
I tried to use an other webserver theme adding it in $HOME/.aMule/webserver/[skin name]/ as explained in [https://wiki.amule.org/wiki/AMuleWeb#Template_.28skin.29_location](https://wiki.amule.org/wiki/AMuleWeb#Template_.28skin.29_location), but when I change the amule.conf with the theme folder's name, the default theme is shown.

**Comment by ngosang** [comment]
It should be possible.
1. Edit the docker-compose.yml to mount the "external theme folder"
```yml
    volumes:
       - "/your_host/theme_path:/usr/share/amule/webserver/your_theme"
```
2. Edit the amule.conf file to set the theme `your_theme`
3. Restart amule container

Make sure the theme and the amule.conf are mounted in an external volume. If not, the changes will be lost when you restart the container.

**Comment by acetaku** [comment]
Thank you for the solution!
