### ISSUE TITLE
MODFIX: Variable Nick

### ISSUE THREAD

**Issue by Lordpedal** [ngosang/docker-amule#25]
Buenas,

Lo primero agradecer el port y su magnifico funcionamiento, un mod sencillo que considero interesante sería poder añadir la variable Nick en los parametros de creación del servicio.

Un saludo

**Comment by ngosang** [comment]
Gracias por el feedback. Creo que está bien así.
El valor por defecto es `Nick=http://www.aMule.org` (el valor por defecto que trae aMule).
Después de arrancar la primera vez puedes editar el fichero `amule.conf` y reiniciar. El fichero solo se crea/modifica si no existe. Cualquier cambio manual es preservado.
