### ISSUE TITLE
Server changes at each auto restart from "default" one

### ISSUE THREAD

**Issue by garret** [ngosang/docker-amule#26]
I would like to connect to a specific server (the one with most files). This is achieved when I start the container. All good until now. However, when the auto restart happens, aMule connects to another server. Is there a way to force aMule to connect only to a specific server (the one I had chosen in the beginning). I know this is a very specific aMule question but wanted to try if you had an idea since official aMule support is not very responsive.

**Comment by ngosang** [comment]
You can have only 1 server in the list.

**Comment by garret** [comment]
I stopped the container, commented with # the line where there is the address to download the server.met file and modified the server.met file by only having the first line with the server I want. However, when restarting the container I get all the servers downloaded again (thus the server.met is overwritten).

**Comment by ngosang** [comment]
Instead of commenting just set an invalid value. Take a look at the other confis:
```
RemoveDeadServer=1
DeadServerRetry=10
ServerKeepAliveTimeout=0
Reconnect=1
Serverlist=0
AddServerListFromServer=0
AddServerListFromClient=0
```

**Comment by garret** [comment]
Thanks, I applied those settings and removed the other lines in the server.met and now I can see only one server.
