### ISSUE TITLE
Feature request: adding curl package to support Telegram Notifications

### ISSUE THREAD

**Issue by Veda82** [ngosang/docker-amule#27]
Hi,

I was wondering if it would be possible to add curl package to the image.
I'm using a simple script to send notifications to my Telegram account, using curl, but every time I restart the docker container I must add the package manually.

Thanks in advance.

**Comment by ngosang** [comment]
It's included in the latest release => https://github.com/ngosang/docker-amule/releases/tag/2.3.3-14
You can extend the Docker image to install packages and to add your scripts.

**Comment by Veda82** [comment]
Thank you! @ngosang
