### ISSUE TITLE
Triple file? (QNAP)

### ISSUE THREAD

**Issue by pyotty** [ngosang/docker-amule#32]
I installed the product on a qnap following the instructions.
All right, connect and download.
Ka files seem to be saved in 3 locations:

/share/MD0_DATA/Container/container-station-data/lib/docker/overlay2/a4bb143a517b84815e451a4e73bdb9af28cda33ed1f4b9188bf95d1dd31eda0e/diff/incoming

/share/MD0_DATA/Container/container-station-data/lib/docker/overlay2/a4bb143a517b84815e451a4e73bdb9af28cda33ed1f4b9188bf95d1dd31eda0e/merged/incoming

/share/MD0_DATA/Container/container-station-data/lib/docker/overlay2/a4bb143a517b84815e451a4e73bdb9af28cda33ed1f4b9188bf95d1dd31eda0e/diff/incoming

What can I check?
Thank you

**Comment by ngosang** [comment]
You have to learn about how Docker volumes work.
In the Docker command there 3 volumes. For each one you map the folder in QNAP with a folder inside the Docker container. Eg: `/home/qnap/downloads:/incoming`. You only have to change the QNAP path, the other must be as it's.
```
    volumes:
      - <fill_amule_configuration_path>:/home/amule/.aMule
      - <fill_amule_completed_downloads_path>:/incoming
      - <fill_amule_incomplete_downloads_path>:/temp
```

The paths in your post are internal from Docker and you don't have to touch them. Your files will be in `/home/qnap/downloads`.
