### ISSUE TITLE
Web UI becomes unresponsive + the download slows down the upload

### ISSUE THREAD

**Issue by Kayn2106** [ngosang/docker-amule#34]
When I add several downloads, like let's say 10 files, then the Web UI becomes unresponsive more and more minute after minute until it takes more than 2 minutes to loads or to show a different UI section. In the worst cases it crashes completely and becomes available again after some time. That's for sure related to the number of files in the download queue because if I stop all of them the Web UI works as normal and even if I download less files at the same time the problem disappears.
Second point if the download is active the upload slows down a lot, it almost disappears; when the download is stopped the upload return to its full speed, within the max cap value of course.

By the way I'm on Unraid OS and I've activated all the mods like the fix for the kad graph and so on...

**Comment by Kayn2106** [comment]
Update: the problem is not related to the number of files in the download queue. The issue starts as soon as even a single download is started. So basically I can only upload, because if I try to download something then the web ui becomes sluggish and by the way even the download speed is not something to write home about... I've tried the same files on a PC with eMule and the speed is way better, I mean ten times more...

**Comment by Kayn2106** [comment]
I don't know if this could help but in the logs I've found this: Command ''amuleweb' '--amule-config-file=/home/amule/.aMule/amule.conf'' with pid '44' has finished with status code '-6'.

Please can someone help a little ? I mean I really wanna sole these problems, but I don't know where to start... Any tip would be very appreciated...

**Comment by ngosang** [comment]
I'm able to download 10 files and share 5k at the same time.
What is your hardware? What is your internet speed?
Could you try to run the aMule Docker in your PC? Could you limit the download speed in aMule?

**Comment by Kayn2106** [comment]
> I'm able to download 10 files and share 5k at the same time. What is your hardware? What is your internet speed? Could you try to run the aMule Docker in your PC? Could you limit the download speed in aMule?

My hardware is a Terramaster F2-423 upgraded with an ssd and 16GB of RAM. My internet speed is 300Mbps DW and 100Mbps UP. As I said above I'm able to run a Windows VM with eMule MorphXT 12.7 ans everything works great. I don't think it's an issue related to my hardware or internet speed....

**Comment by ngosang** [comment]
aMule is a really old software but it's working fine for me. I can share thousands of files and reach an upload/download speed of 20MB/s. eMule is better software but it doesn't have a version for Linux and it doesn't have web Ui. I have aMule running 24/7 in my NAS for 5 years now.

Notice that I'm not aMule developer. I just pack the latest release as Docker image. You can try installing aMule in Windows without Docker. Just plain exe. https://github.com/minnyres/amule-win32/releases/tag/v2.3.3.4

**Comment by Kayn2106** [comment]
> aMule is a really old software but it's working fine for me. I can share thousands of files and reach an upload/download speed of 20MB/s. eMule is better software but it doesn't have a version for Linux and it doesn't have web Ui. I have aMule running 24/7 in my NAS for 5 years now.
> 
> Notice that I'm not aMule developer. I just pack the latest release as Docker image. You can try installing aMule in Windows without Docker. Just plain exe. https://github.com/minnyres/amule-win32/releases/tag/v2.3.3.4

Yes I know that, I'm a long time eMule user too ;) No intention to bother you or suggest that my problems are your fault. As you said aMule is a really outdated software so it is what it is... Maybe I'll continue to run eMule in the VM and I'll let go the idea of running a native Linux version...

**Comment by Kayn2106** [comment]
Finally I managed to understand the cause of the problem. I had gave up on using aMule on the NAS, so I after few days I installed windows and eMule MorphXT on the NAS. When I added the downloads the same thing happens : the ui was freezing, the software became unresponsive for quite a bit and even the connection got stuck in both direction no download an no more upload. 
I added 15 files for a total of 180GB and I noticed that the HDD utilization immediately spikes at 100% and stays at that level quite a bit, as soon as the HDD turns at normal operation level the ui works again. 

Keep it short, the problem is the "alloc full disk space for .parts file". In the MorphXT there's the option "create new file .part as sparse" if I active that option the problem is gone...

So far so good, however I don't know how aMule manages .part files; I mean for sure that's no such option in the settings. Maybe there's a way to active that through the amule.conf file ? Or maybe the sparse option is the default behavior, so I simply could not flag the "alloc full..." option ? Do you happen to know something about this ?
