### ISSUE TITLE
Webui crash

### ISSUE THREAD

**Issue by Kayn2106** [ngosang/docker-amule#35]
Sorry to bother you again, but I've to reopen this topic because finally I managed to understand the cause of the problem. I had gave up on using aMule on the NAS, so I after few days I installed windows and eMule MorphXT on the NAS. When I added the downloads the same thing happens : the ui was freezing, the software became unresponsive for quite a bit and even the connection got stuck in both direction no download an no more upload.
I added 15 files for a total of 180GB and I noticed that the HDD utilization immediately spikes at 100% and stays at that level quite a bit, as soon as the HDD turns at normal operation level the ui works again.

Keep it short, the problem is the "alloc full disk space for .parts file". In the MorphXT there's the option "create new file .part as sparse" if I active that option the problem is gone...

So far so good, however I don't know how aMule manages .part files; I mean for sure that's no such option in the settings. Maybe there's a way to active that through the amule.conf file ? Or maybe the sparse option is the default behavior, so I simply could not flag the "alloc full..." option ? Do you happen to know something about this ?

**Comment by ngosang** [comment]
I see these options in the Web UI:
![image](https://github.com/ngosang/docker-amule/assets/10577978/c2d3b079-c516-4571-99ba-4930e7f697a3)
You can try to change them before downloading the files to see if it makes any difference. After changing those settings restart aMule just to be sure they are applied.

Btw, new release => https://github.com/ngosang/docker-amule/releases/tag/2.3.3-15

**Comment by marcospm92** [comment]
Any news on this topic [Kayn2106](https://github.com/Kayn2106)? I am facing the same issue

**Comment by Kayn2106** [comment]
> Any news on this topic [Kayn2106](https://github.com/Kayn2106)? I am facing the same issue

After I've deselect both "Alloc full chunks" ans "Alloc full disk space" everything is going on without any issues...
