### ISSUE TITLE
Writing buffer option?

### ISSUE THREAD

**Issue by HeuristicPerson** [ngosang/docker-amule#36]
I've noticed that the HDD activity is quite high when downloading anything, even at low speeds, much higher than any torrent download. Could it be a writing buffer issue? is there any option or way to have such buffer by changing amule configuration or even the container?

Regards and many thanks for the image.

**Comment by HeuristicPerson** [comment]
Just a note in case I forget it later. Changing FileBufferSizePref=1500 seems to solve the issue. Not enough evidence since I'm downloading a file without too much activity.

**Comment by ngosang** [comment]
I changed the FileBufferSizePref=1400. This only applies to new installations. If you are already using this container you should update `admule.conf`file.
Default value was 16 (234 KB), new value 1400 (20 MB).

http://forum.amule.org/index.php?topic=13519.msg93963#msg93963

**Comment by ngosang** [comment]
https://github.com/ngosang/docker-amule/releases/tag/2.3.3-16
