### ISSUE TITLE
problem with locale

### ISSUE THREAD

**Issue by Vctrsnts** [ngosang/docker-amule#4]
Hello

I am using your Docker image with Debian on Raspberry Pi 4 (arm64). The system is configured with es_ES.UTF-8.

But the problem is that when I download a file with Spanish words (á, ñ, etc ...) in the client's amule, I see the file correct, but when I do "ls" to access the directory with filezilla I see (for example ):

    el.dia.de.mañana.(2010).mkv (the name of the file on the amule client) -> el.dia.de.ma\03ana.(2010).mkv (with filezilla client)

Another example is that I use flexget to find the original name and copy another directory, but when it looks for the information and reaches the sample file, the system breaks because it indicates that it has found strange characters (\03).

On the other hand, if I use the original docker the synopsis8 (which indicates that it has inspired you) also on a Raspberry Pi 4 (armhf) work perfectly and configure with same locale ( es_ES.UTF-8 ).

Do you know where the problem can come from? I comment on it, because I have tried (inside the container) to install the package "locales" and configure it as es_ES.UTF-8 but the problem is still not solved

Thanks a lot

**Comment by ngosang** [comment]
I was having the same issue but you give me the clue with the locale. Test the new Docker image `2.3.3-3`

**Comment by ngosang** [comment]
@Vctrsnts did it work? ¿funcionó?

**Comment by Vctrsnts** [comment]
Hello,

At the moment everything is ok.

I have used it with Raspberry Pi OS (armhf) and GNU/Debian ARM64 and it works perfectly.

The only thing left for me to test is access through WEBUI, but I think it's my problem when configuring it. Because through amule gui it works perfectly.

Thanks again for all the work you do.

**Comment by ngosang** [comment]
Nice. I have the WebUI working so it's possible.
I also recommend you to setup a "cron" or some kind of scheduler to restart the Docker container once a week. aMule has a memory leak and the memory increases over the time. It's not really big but some Raspberry Pi have few RAM.

I restart mine every 2 days.
![image](https://user-images.githubusercontent.com/10577978/149637543-4c3ab68b-80fe-4cd5-b90d-a70f47db025d.png)

**Comment by Vctrsnts** [comment]
Thanks for everything,

Yes, let's see if I can find where I incorrectly configure the WEBUI.
But regarding the ram memory bug, I have never had any problem and I have been using it for a long time, even with the first version of RPI that had 512Mb and no problem.
The only problem I have is that when I delete a file, the client closes, but the daemon continues as if nothing had happened.
And I tell you, amulet, it can be at least a month without restarting or more and everything works perfectly.

Thanks for everything
