### ISSUE TITLE
[Enhancement] Add Stop file button

### ISSUE THREAD

**Issue by Kayn2106** [ngosang/docker-amule#40]
This is a enhancement suggestion. Let's say you're downloading a series of files with very few sources and you know that all these files shares the same complete source/sources. If you pause all the files in order to download them one by one the sources that have been found previously remain "trapped" as A4AF sources; so you have to be able to stop the files in such a way as to "unlock" the sources that so could be contacted for another file. 

Another reason may be, always in relation to the previous situation, if you want to know if a file has or not at least one complete source. If a complete source is stucked as A4AF source in another queue you can't contact it and so the file is shown as incomplete when instead it is not...

Of course these are only some of many reasons why someone would want to be able to stop and not pause a file.

**Comment by ngosang** [comment]
This repository is just for packaging aMule in a Docker container.
If you have improvements/enhancements/bugs for aMule you have to [create the issues here](https://github.com/amule-project/amule), but they are not very active.
