### ISSUE TITLE
cant access webui raspberry pi 4

### ISSUE THREAD

**Issue by nicobellic1** [ngosang/docker-amule#45]
Hi, I am trying to run your container on a raspberry pi 4, but I cant login to the webui and the logs show that it's stuck in a loop. I tried deleting all files and retrying but it had no effect. I started the compose file with docker compose up -d. 

This is my docker-compose.yml: 
[docker-compose.txt](https://github.com/ngosang/docker-amule/files/14098359/docker-compose.txt)

portainer logs: 
[_amule_logs.txt](https://github.com/ngosang/docker-amule/files/14098364/_amule_logs.txt)

**Comment by ngosang** [comment]
Try setting MOD_FIX_KAD_BOOTSTRAP_ENABLED=false

**Comment by nicobellic1** [comment]
Thanks for your response, today I got aware of your answer and I simply deleted all config files and tried again. Everything works now
