### ISSUE TITLE
Connection lost when VPN changes server

### ISSUE THREAD

**Issue by Kayn2106** [ngosang/docker-amule#46]
I'm on Unraid and I'm routing aMule through Gluetun VPN and everything works fine, but when the VPN goes down then after Gluetun has established a new connection then aMule no longer works. No traffic in both directions until it's been restarted, then it gets back working as usual. 
I've already tried with Rebuild-DNDC, but since the connection drop lasts 5 seconds when it checks the connection status it's already healty again, so from its point of view there's no need to rebuild the containers routed to the VPN connection. 

Any possible solution ? Thanks

**Comment by ngosang** [comment]
You can make a script to check if the VPN has changed (checking the logs of something similar) and restart the aMule container.
I'm closing this issue since it's a network problem.
