### ISSUE TITLE
Can't get it to work with NPM reverse proxy

### ISSUE THREAD

**Issue by lockheed** [ngosang/docker-amule#48]
I have tens of services working find, but I can't get Amule to work with NginxReverse Proxy Manager. Whatever I set, I always get "502 Bad Gateway". Any ideas what could be wrong here? I tried various ports already (also set in remote.conf).

**Comment by ngosang** [comment]
You must be doing something wrong in the reverse proxy configuration. I have mine running behind Trafik reverse proxy and it's fine. aMule Web UI is very standard.

**Comment by lockheed** [comment]
Nope. I since moved to Caddy and still no webgui. But I am using remote app gui so it doesn't matter anymore.
