### ISSUE TITLE
Statistics are not saved

### ISSUE THREAD

**Issue by Carlos672** [ngosang/docker-amule#50]
Hi, 
Running amule on docker container on a raspberry 4.

Statistics are not saved, it means that transferred bytes, requests and accepted requests are lost every time the container is restarted.

**Comment by ngosang** [comment]
There are session stats (they are lost after the restart) and global stats (they are saved). We can't change that, I just releasing aMule packaged in a Docker container. That king of changes must be done in the aMule project.

![image](https://github.com/user-attachments/assets/fa950d7e-907f-442f-9bf3-9c1f08e18162)

**Comment by Carlos672** [comment]
Sorry if I didn't explain properly, these statistics works the way they intended to work but on the "shared files" tab the total stats from every file is reset every time the container is restarted.

![image](https://github.com/user-attachments/assets/cffef0e6-3a81-4cef-971b-bedc6158be50)

**Comment by ngosang** [comment]
Those stats are saved. I can see them in the Web UI at least.
Anyway, if you want to report this issue you should do it in the official project => https://github.com/amule-project/amule

![image](https://github.com/user-attachments/assets/15250ad2-00b6-4d55-8ecd-2bf55e6e15d5)
