### ISSUE TITLE
Access without password

### ISSUE THREAD

**Issue by adriaurora** [ngosang/docker-amule#52]
Hi, I've installed amule a few weeks ago and I've been trying since then to quit the password access without success, is any way to bypass it? As I've Traefik installed and the log in is done via Authelia I don't want this password protection.

I don't know if it is possible, but it would be nice to have a variable in the docker container setting to disable it.

Thanks in advance.

**Comment by ngosang** [comment]
I don't think it's possible to disable the password in the WebUI.
In the amule.conf file there are 2 "password" fields. You can try to remove those fields and see if the Docker container starts. You can also try to search "amule webui password" in Google.
