### ISSUE TITLE
Route just amule container traffic over VPN

### ISSUE THREAD

**Issue by toketin** [ngosang/docker-amule#55]
Hi, since my internet connection is behind NAT I've to use a VPN with all traffic routed through it, in order to get an high ID on amule. 

Today I've read here: [https://wiki.archlinux.org/title/WireGuard#systemd-networkd:_routing_all_traffic_over_WireGuard](https://wiki.archlinux.org/title/WireGuard#systemd-networkd:_routing_all_traffic_over_WireGuard), chapter _Route for specific user_, that with Wireguard you can route WAN traffic over the tunnel only for a specific user, it's done the example of the transmission user in order to use the tunnel for torrent traffic. 

I was wondering if there's any chance to get this same behaviour using this good amule container and wireguard. Do you know if is it feasible?

Thanks in advance!

**Comment by toketin** [comment]
Solved, I've been able to achieve this using gluetun docker container.

**Comment by ngosang** [comment]
I'm closing the issue since it's out of the scope of this repository, but it could be helpful for others.
