### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by orinsid** [ngosang/docker-amule#56]
I would like to ask how to use the proxy? I know there is a [proxy] setting in the amule.conf file, but after I set it up, the program cannot connect to the kad server. My proxy uses socks5. I don't know if there is something wrong with my configuration?
[Proxy]
ProxyEnableProxy=1
ProxyType=2
ProxyName=192.168.1.2
ProxyPort=1080
ProxyEnablePassword=
ProxyUser=
ProxyPassword=

**Comment by ngosang** [comment]
I don't know much about the Proxy in aMule. You should read the official documentation => http://wiki.amule.org/wiki/Usage_Preferences#Proxy
In my experience the Proxys don't work well with UDP traffic and they can leak information like DNS requests, IPfilter download... To use a VPN is easier to configure and more secure.
