### ISSUE TITLE
webgui disabled?

### ISSUE THREAD

**Issue by Koradris** [ngosang/docker-amule#6]
hi , the webgui on port 4712 is disabled?

**Comment by ngosang** [comment]
That is not the Web UI port. Web UI is enabled by default on port `4711`. You can set the password with the environment variable `WEBUI_PWD`. Take a look at the first lines of the log.

Port `4712` is for the remote desktop client.

https://github.com/ngosang/docker-amule/blob/eda654c340979a4f76731b2c376188a93c2ff672/docker-compose.yml#L14
